apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker-daemon
      image: docker:20.10.12-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: docker
      image: docker:20.10.12
      command: ['sleep', '99d']
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375